version: "3"

services: 
    app: # service name
        build: # build configuration for current directory (.)
            context: .
        ports: 
            - "8000:8000"
        volumes: # maps volume from local machine to docker image (e.g. for updates)
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db && 
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=DB
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword!*
        depends_on: 
            - db

    db:
        image: postgres:12-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword!*
