version: "3"

services: 
    app: # service name
        build: # build configuration for current directory (.)
            context: .
        ports: 
            - "8000:8000"
        volumes: # maps volume from local machine to docker image (e.g. for updates)
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"